### ISSUE TITLE
Ubuntu 18.10 Base Image

### ISSUE THREAD

**Issue by incizzle** [sr229/code-server-openshift#3]
I think creating a separate image with Ubuntu 18.10 would be a nice addition so devs are familiar with the environment and don't need to install basic commands like git and nano.

**Comment by sr229** [comment]
I actually have Git installed on these images, however, I'm planning to move this to 18.10 soon fwiw

**Comment by sr229** [comment]
@incizzle can you try building the `master` branch? I just recently moved the stack to 18.10 and it should be ready to be in `release`
